### PR TITLE
Add option to pass ref down to underlying component

### LINKED ISSUE #67: Possible to assign a ref to UI component?
Trying to refactor a component to a contained/pure pair. This is a web RTC component, so at some point I need to attach audio/video streams to `<video/>` elements contained in the UI. In order to keep the component pure, this needs to be done in the container logic.

Is there any way to render the UI component with a known, fixed ref? Then I could call this.refs.ui.refs.localVideo or this.refs.ui.refs.remoteVideo to get access to the contained video elements. I recognize this is ugly, but the only other way I can think to do this is to assign ids to the video elements, and that's even uglier. :) Open to any other suggestions on how the container component can access elements in the UI component. I can almost guarantee the UI component will be mounted and visible at the point where the elements need to be accessed, so I'm not concerned about it not being available at time of use.

Thanks.

### PR DESCRIPTION
**Pull request by clayne11**
Fixes #67

### CODE REVIEW

**Comment by arunoda** [comment]
I don't understand the use case of this. (May be I'm bit wrong on this).
Could you add the use case of this API as a test case?

**Comment by clayne11** [comment]
To test it fully I need to use full DOM rendering. Do you want me to set up a test with JSDOM?

**Comment by arunoda** [comment]
Hmm. May be we need it. Try this: https://github.com/kadira-samples/react-button/blob/master/.scripts/mocha_runner.js

**Comment by clayne11** [comment]
I added a test to display the functionality using `JSDOM`.

**Comment by arunoda** [comment]
Got it. Thanks.

**Pull request merged**
