### PR TITLE
Add loading and error react-native components

### PR DESCRIPTION
**Pull request by superandrew213**
@arunoda what do you think about this? We can conditionally require instead of importing. Require will only trigger if we are in react-native environment.

### CODE REVIEW

**Comment by arunoda** [comment]
I think this will be great.
I think we can take this this in.

Do you have anything else to do before I take this in?

**Comment by superandrew213** [comment]
I don't think so. Do you want me to change anything?

**Comment by arunoda** [comment]
I think this is great.

**Comment by arunoda** [comment]
@superandrew213 I had to revert this PR since it breaks some tests but that can be fixed easily. But, babel warns because of not having react-native as a dependency.

(do npm test)

I want some ideas to fix this.

**Comment by superandrew213** [comment]
@arunoda ok I will have a look

**Comment by superandrew213** [comment]
Since npm3 peer dependencies will not be installed anymore and it will give a warning if they can't be found. 

Fixed the eslint errors.

mocha throws `ReferenceError: navigator is not defined`

We could just add `global.navigator = {};`

What do you think?

**Comment by arunoda** [comment]
Or we could do something like `type navigator !== 'undefined' && navigator.XXXX = 'OTHER CHECK'`. I like that much.

I'm not getting the npm peer-dep error. Try doing `npm run prepublish`. That's the final version will be send to the NPM. That's where we get the error.

**Comment by superandrew213** [comment]
oh ok got you

**Comment by superandrew213** [comment]
@arunoda I think that error is caused by browserify

**Comment by superandrew213** [comment]
Adding `--ignore-missing` to `browserify --debug --ignore-missing -t [ exposify --expose [ --react React ] ] ./window_bind.js > ./browser.js` removes the error

**Comment by superandrew213** [comment]
Made all the necessary changes and am not getting any errors anymore. Let me know if it's all good on your side.

**Comment by arunoda** [comment]
Okay. This is perfect for me. Could you send me another PR. 

Can't wait to take this in.

**Comment by superandrew213** [comment]
Done!

**Pull request merged**
