### PR TITLE
Add loading and error react-native components

### PR DESCRIPTION
**Pull request by superandrew213**

### CODE REVIEW

**Comment by arunoda** [comment]
Thanks.

**Comment by arunoda** [comment]
Released as `v1.5.0`

**Comment by arunoda** [comment]
This works, but this leads the same error as browserify with webpack. So, had to do this:

https://github.com/kadirahq/react-komposer/commit/26d02fe8adba836cf6bd52903daf3286f214a63f

We will need to work on a better way to load default configurations like error and loading components. Then this won't be an issue at all.

**Comment by arunoda** [comment]
See: https://github.com/kadirahq/react-komposer/issues/8

**Comment by superandrew213** [comment]
hmm ok. Will let you know if I come up with something better.

**Comment by arunoda** [comment]
Awesome.

**Pull request merged**
