### PR TITLE
React 16 peerDependencies fix

### PR DESCRIPTION
**Pull request by Coobaha**

### CODE REVIEW

**Comment by brucewpaul** [comment]
Is there anything holding this back from being merged and released?

**Comment by loanlaux** [comment]
More importantly: is someone still maintaining this project? I see that the last commit on master was a long time ago.

**Comment by bogas04** [comment]
@arunoda would it be possible for you to merge this PR ? Thanks !

**Comment by PierreAndreis** [comment]
+1

**Comment by danielduan** [comment]
We forked, fixed, and published this package as `@storybook/react-komposer` if you're interested in using it. @Coobaha @loanlaux @bogas04 @PierreAndreis

**Comment by fortuneNyl** [comment]
I use @storybook/mantra-core in a meteor v1.6.1 app, with react@16.2.0. But a have a problem with the composeWithTracker function. This function have been taken off react-komposer@2, used by storybook, but is still declared in @storybook/mantra-core/dist/index. So, I have a question. How could I send data from my containers to my components? Need help please.

**Pull request closed without merging**
