### PR TITLE
Add dedicated composer for MobX

### PR DESCRIPTION
**Pull request by markoshust**

### CODE REVIEW

**Comment by markoshust** [comment]
@arunoda all set. I've never written any production js tests before (i know, 😲 ), so please check them out. I think they should be pretty good to go though.

**Comment by markoshust** [comment]
The disposer wasn't properly being returned before. All tested, now properly being returned to run the cleanup function if needed.

**Comment by arunoda** [comment]
I think this is great. Let me get this PR.

**Comment by arunoda** [comment]
Merged and published with `v1.13.0`. 
Thanks and your tests are great :)

**Comment by markoshust** [comment]
Great, the other examples helped 👍

**Pull request merged**
